import * as THREE from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import { A } from './assets.js';

// Exterior skin of the outer-ring towers (supplied residential models). Interiors come from building.js; this is the one-sided shell.

// quantized (KHR_mesh_quantization) attributes are integers: expand to float before any matrix is baked in
function toFloat(src) {
  const g = new THREE.BufferGeometry();
  for (const name of ['position', 'normal', 'uv']) {
    const a = src.attributes[name]; if (!a) continue;
    const f = new Float32Array(a.count * a.itemSize);
    for (let i = 0; i < a.count; i++) { f[i * a.itemSize] = a.getX(i); f[i * a.itemSize + 1] = a.getY(i); if (a.itemSize > 2) f[i * a.itemSize + 2] = a.getZ(i); }
    g.setAttribute(name, new THREE.BufferAttribute(f, a.itemSize));
  }
  if (src.index) g.setIndex(Array.from(src.index.array));
  return g;
}

// The supplied meshes also contain faces that look into the building. They are fine from outside, but the interiors generated by
// building.js sit inside this shell, so keep only roofs and vertical faces that point away from the footprint centre.
function outwardOnly(src) {
  const g = src.index ? src.toNonIndexed() : src, pos = g.attributes.position, nor = g.attributes.normal, uv = g.attributes.uv;
  const keep = [], a = new THREE.Vector3(), b = new THREE.Vector3(), c = new THREE.Vector3(), n = new THREE.Vector3();
  for (let i = 0; i + 2 < pos.count; i += 3) {
    a.fromBufferAttribute(pos, i); b.fromBufferAttribute(pos, i + 1); c.fromBufferAttribute(pos, i + 2);
    n.crossVectors(b.clone().sub(a), c.clone().sub(a)); if (n.lengthSq() < 1e-12) continue; n.normalize();
    if (n.y > 0.5) { keep.push(i); continue; }      // roofs, ledges
    if (n.y < -0.5) continue;                       // undersides are never seen
    const rx = (a.x + b.x + c.x) / 3, rz = (a.z + b.z + c.z) / 3, rl = Math.hypot(rx, rz) || 1;
    if ((n.x * rx + n.z * rz) / rl >= -0.1) keep.push(i);
  }
  const out = new THREE.BufferGeometry();
  for (const [name, attr] of [['position', pos], ['normal', nor], ['uv', uv]]) {
    if (!attr) continue;
    const f = new Float32Array(keep.length * 3 * attr.itemSize);
    keep.forEach((t, k) => { for (let v = 0; v < 3; v++) for (let q = 0; q < attr.itemSize; q++) f[(k * 3 + v) * attr.itemSize + q] = attr.array[(t + v) * attr.itemSize + q]; });
    out.setAttribute(name, new THREE.BufferAttribute(f, attr.itemSize));
  }
  return out;
}

let wallTex = null;
function wallMaterial(url) {
  if (wallTex) return wallTex;
  const t = new THREE.TextureLoader().load(url); t.wrapS = t.wrapT = THREE.RepeatWrapping; t.colorSpace = THREE.SRGBColorSpace; t.anisotropy = 4; t.flipY = false;
  const m = new THREE.MeshStandardMaterial({ map: t, color: 0x9db0d4, roughness: 0.9, metalness: 0.0, envMapIntensity: 0.5 });
  haze(m);
  return (wallTex = m);
}
// Fog is far too dense for a skyline (everything past ~200 m is flat colour), so these materials use a much thinner haze.
function haze(m) {
  m.onBeforeCompile = (sh) => {
    // entrance face: open the glazed ground-floor bays (between 0.7 m pillars) so the lobby is visible, same rule as the city facades
    sh.vertexShader = sh.vertexShader
      .replace('#include <common>', '#include <common>\nattribute vec4 aDoor;varying vec4 vDoorS;varying vec3 vWPs;varying vec3 vWNs;')
      .replace('#include <begin_vertex>', '#include <begin_vertex>\nvDoorS=aDoor;vWPs=(modelMatrix*vec4(transformed,1.)).xyz;vWNs=normalize(mat3(modelMatrix)*objectNormal);');
    sh.fragmentShader = sh.fragmentShader
      .replace('#include <common>', '#include <common>\nvarying vec4 vDoorS;varying vec3 vWPs;varying vec3 vWNs;')
      .replace('#include <color_fragment>', `#include <color_fragment>
      if(vDoorS.w>.5&&vWPs.y>.3&&vWPs.y<3.1){
        vec3 Ns=normalize(vWNs);float code=Ns.x<-.5?0.:(Ns.x>.5?1.:(Ns.z<-.5?2.:(Ns.z>.5?3.:-1.)));
        if(abs(code-vDoorS.z)<.5){float h=abs(Ns.x)>.5?vWPs.z:vWPs.x;float f=fract((h-vDoorS.x)/vDoorS.y);float pw=.35/vDoorS.y;if(f>pw&&f<1.-pw)discard;}
      }`)
      .replace('#include <fog_fragment>', `#ifdef USE_FOG
      float ff = 1.0 - exp(-fogDensity * fogDensity * vFogDepth * vFogDepth * 0.04);
      gl_FragColor.rgb = mix(gl_FragColor.rgb, fogColor, ff);
    #endif`);
  };
  m.customProgramCacheKey = () => 'skyline-haze-door';
}

export function buildSkyline(scene, world, wallUrl) {
  const lots = world.lots.filter((l) => l.model);
  if (!A.res || !lots.length) return null;
  const wall = wallMaterial(wallUrl);
  const glass = new THREE.MeshStandardMaterial({ color: 0x1a2c44, roughness: 0.08, metalness: 0.7, emissive: 0xffc27a, emissiveIntensity: 0, envMapIntensity: 1.2 });
  haze(glass);
  (world.nightEmit = world.nightEmit || []).push({ m: glass, k: 0.9 });
  const parts = {};
  for (const i of new Set(lots.map((l) => l.model.variant))) {
    const prim = [];
    A.res[i].traverse((o) => { if (o.isMesh) { const g = outwardOnly(toFloat(o.geometry).applyMatrix4(o.matrixWorld)); prim.push({ g, glass: /glass/i.test(o.material.name) }); } });
    parts[i] = prim;
  }
  // One merged wall mesh and one merged glass mesh per side of the ring, so frustum culling drops whole sides.
  const group = new THREE.Group(); group.name = 'skyline';
  const m4 = new THREE.Matrix4(), rq = new THREE.Quaternion(), ax = new THREE.Vector3(0, 1, 0), one = new THREE.Vector3(1, 1, 1), pv = new THREE.Vector3();
  for (const side of ['n', 's', 'w', 'e']) {
    const wallG = [], glassG = [];
    for (const l of lots) {
      if (l.model.side !== side) continue;
      rq.setFromAxisAngle(ax, l.model.rot); pv.set(l.model.cx, 0, l.model.cz); m4.compose(pv, rq, one);
      const d = l.door, dv = d ? [d.nx !== 0 ? l.z0 : l.x0, d.bay, { w: 0, e: 1, n: 2, s: 3 }[d.side], 1] : [0, 1, 0, 0];
      for (const p of parts[l.model.variant]) {
        const g = p.g.clone().applyMatrix4(m4), n = g.attributes.position.count, a = new Float32Array(n * 4);
        for (let i = 0; i < n; i++) a.set(dv, i * 4);
        g.setAttribute('aDoor', new THREE.BufferAttribute(a, 4));
        (p.glass ? glassG : wallG).push(g);
      }
    }
    const add = (geos, mat) => {
      if (!geos.length) return;
      const g = mergeGeometries(geos.map((q) => (q.index ? q.toNonIndexed() : q)), false); if (!g) return;
      const mesh = new THREE.Mesh(g, mat); mesh.receiveShadow = false; mesh.castShadow = false; g.computeBoundingSphere(); group.add(mesh);
    };
    add(wallG, wall); add(glassG, glass);
  }
  scene.add(group);
  return { group, count: lots.length };
}
