(()=>{'use strict';
const now=()=>new Date().toISOString(),finite=Number.isFinite,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const AETHER=window.AETHER=Object.seal({VERSION:'0.13.5-M19-IMPLEMENTATION',MILESTONE:'M13_CFD_SCIENTIFIC_VISUALIZATION',BASELINE:null,CURRENT_AUTHORITIES:null,DIAGNOSTICS:null,APPLICATION:null,COORDINATE_CONTRACT:null,WIND_TUNNEL_CONFIG:null,VEHICLE_TRANSFORM:null,ROLLING_ROAD:null,M4_CONFIG:null,CFD_DOMAIN:null,CFD_BRIDGE:null,SCIENTIFIC_VIS:null,M1:null,M3:null,M4:null,M5:null,M6:null,M7:null,M8:null,M9:null,M10:null,M11:null,M12:null,M13:null,M14:null,M15:null,S3:null,S3_OFFICE:null,S2:null,S1:null,SOLVER:null,MATERIALS:null,VEHICLE_PRODUCTION:null,FAN_MODULE:null,FLOW_LAYOUT:null,EXHAUST_COLLECTOR:null,ASSETS:null});
const diagnostics={startedAt:now(),events:[],errors:[],warnings:[],_bootStage:'BOOT',bootStageStartedAt:now(),bootStageTimes:[],get bootStage(){return this._bootStage},set bootStage(stage){const t=now();if(this._bootStage!==stage)this.bootStageTimes.push({stage:this._bootStage,next:stage,elapsedMs:t-this.bootStageStartedAt,totalMs:t-this.startedAt});this._bootStage=stage;this.bootStageStartedAt=t},contractReady:false,facilityReady:false,vehicleReady:false,texturesReady:false,event(type,message,detail=null){this.events.push({time:now(),type,message,detail});renderDiagnostics()},error(source,e){const x={time:now(),source,name:e?.name||'Error',message:e?.message||String(e),stack:e?.stack||null};this.errors.push(x);this.events.push({time:now(),type:'ERROR',message:source+': '+x.message});return x}};AETHER.DIAGNOSTICS=diagnostics;
const baseline={contractVersion:2,milestone:'M0_BASELINE_FROZEN',mode:'USER_CONFIRMED_STABLE_REFERENCE',frozenAt:'2026-09-28T00:00:00Z',runtime:{secureContext:window.isSecureContext,webGL2Exposed:false,devicePixelRatio:devicePixelRatio,viewport:{width:innerWidth,height:innerHeight}},review:{status:'FROZEN_FROM_USER_CONFIRMED_V40; STATIC_AUDIT_COMPLETE',browserRuntimeVerified:false,baselineRunReported:true,m0Pass:true},authorities:{rendererAuthority:'M4 WebGL2 renderer',gpuDeviceAuthority:'No GPUDevice in the WebGL renderer; optional WebGPU device is owned by AETHER.SOLVER',sceneAuthority:'M4 SceneRegistry',vehicleAuthority:'AETHER.VEHICLE_TRANSFORM + embedded BMW M4 GT3 EVO geometry',solverAuthority:'AETHER.SOLVER S0 shell; production solver not connected',stateAuthority:'M4 rolling-road adapter',cameraAuthority:'M4 CameraController',inputAuthority:'M4 InputController',uiAuthority:'M4 DOM diagnostics'},coordinateContract:{unit:'meter',unitsPerWorldUnit:1,vehicleForward:'-X',airflowDownstream:'+X',up:'+Y',lateral:'+Z'},auditFacts:['M4 WebGL2 renderer; no GPUDevice on the WebGL renderer.','Optional WebGPU device ownership belongs to AETHER.SOLVER.','M4 SceneRegistry.','AETHER.VEHICLE_TRANSFORM + embedded BMW M4 GT3 EVO geometry.','AETHER.SOLVER is an S0 shell; production solver is not connected.','M4 rolling-road adapter; M4 CameraController; M4 InputController; M4 DOM diagnostics.','Canonical coordinate target for M1: 1 unit = 1 m; +X downstream; vehicle nose -X; +Y up; +Z lateral.','v40 baseline runtime was user-confirmed in prior work; browser runtime was not rerun in this turn.']};baseline.coordinateContract={unit:'meter',unitsPerWorldUnit:1,vehicleForward:'-X',airflowDownstream:'+X',up:'+Y',lateral:'+Z'};AETHER.BASELINE=baseline;
AETHER.CURRENT_AUTHORITIES={renderer:'M4 WebGL2 production geometry renderer',gpuDevice:null,scene:'M4 SceneRegistry',vehicle:'AETHER.VEHICLE_TRANSFORM + imported BMW M4 GT3 EVO geometry',cfdDomain:'CFD_DOMAIN_CONTRACT derived from AETHER.WIND_TUNNEL_CONFIG.testSection + COORDINATE_CONTRACT',cfdBridge:'AETHER.CFD_BRIDGE / AETHER.VEHICLE_TRANSFORM shared authority',scientificVisualization:'AETHER.SCIENTIFIC_VIS / M13 dedicated WebGL2 scientific renderer',solver:null,state:'M4 rolling road state adapter',camera:'M4 CameraController',input:'M4 InputController',ui:'M4 DOM diagnostic shell',renderLoop:'M4 requestAnimationFrame',resources:'M4 WebGL resources + M13 derived resources'};
/* Lossless render optimisations. Each can be switched off for A/B checks or as a fallback: #opt=novao,nocull,nosplit (or window.__OPT at runtime). */
const OPT=window.__OPT={vao:!/opt=[^&]*novao/.test(location.hash),cull:!/opt=[^&]*nocull/.test(location.hash),split:!/opt=[^&]*nosplit/.test(location.hash),stats:{culled:0,drawn:0}};
/* Mobile mode: chosen by what the device is (touch as primary input + phone-sized screen), never by the user-agent string, and never to
   guess performance - the quality tier is still measured. Override: #mobile=1 / #mobile=0, or the in-page toggle (stored per browser). */
const MOBILE=window.__MOBILE=(()=>{const o=(location.hash.match(/mobile=([01])/)||[])[1];if(o!==undefined)return o==='1';try{const v=localStorage.getItem('aether.mobile');if(v==='0'||v==='1')return v==='1'}catch(_){}
 try{return matchMedia('(pointer: coarse)').matches&&Math.min(innerWidth,innerHeight)<=820}catch(_){return false}})();
document.documentElement.classList.toggle('mobile',MOBILE);if(document.body)document.body.classList.toggle('mobile',MOBILE);else addEventListener('DOMContentLoaded',()=>document.body.classList.toggle('mobile',MOBILE));
window.__setMobile=v=>{try{localStorage.setItem('aether.mobile',v?'1':'0')}catch(_){}location.hash=location.hash.replace(/[#&]?mobile=[01]/,'')||'';location.reload()};
